// tslint:disable:no-namespace
// tslint:disable:no-shadowed-variable
export { u8 } from './protocol.primitives.u8';
export { u16 } from './protocol.primitives.u16';
export { u32 } from './protocol.primitives.u32';
export { u64 } from './protocol.primitives.u64';
export { i8 } from './protocol.primitives.i8';
export { i16 } from './protocol.primitives.i16';
export { i32 } from './protocol.primitives.i32';
export { i64 } from './protocol.primitives.i64';
export { f32 } from './protocol.primitives.f32';
export { f64 } from './protocol.primitives.f64';
export { bool } from './protocol.primitives.bool';
export { StrUTF8 } from './protocol.primitives.string.utf8';
export { ArrayU8 } from './protocol.primitives.array.u8';
export { ArrayU16 } from './protocol.primitives.array.u16';
export { ArrayU32 } from './protocol.primitives.array.u32';
export { ArrayU64 } from './protocol.primitives.array.u64';
export { ArrayI8 } from './protocol.primitives.array.i8';
export { ArrayI16 } from './protocol.primitives.array.i16';
export { ArrayI32 } from './protocol.primitives.array.i32';
export { ArrayI64 } from './protocol.primitives.array.i64';
export { ArrayF32 } from './protocol.primitives.array.f32';
export { ArrayF64 } from './protocol.primitives.array.f64';
export { ArrayBool } from './protocol.primitives.array.bool';
export { ArrayStrUTF8 } from './protocol.primitives.array.string.utf8';
export { Option, Enum } from './protocol.primitives.enum';

import { u8 } from './protocol.primitives.u8';
import { u16 } from './protocol.primitives.u16';
import { u32 } from './protocol.primitives.u32';
import { u64 } from './protocol.primitives.u64';
import { i8 } from './protocol.primitives.i8';
import { i16 } from './protocol.primitives.i16';
import { i32 } from './protocol.primitives.i32';
import { i64 } from './protocol.primitives.i64';
import { f32 } from './protocol.primitives.f32';
import { f64 } from './protocol.primitives.f64';
import { bool } from './protocol.primitives.bool';
import { StrUTF8 } from './protocol.primitives.string.utf8';
import { ArrayU8 } from './protocol.primitives.array.u8';
import { ArrayU16 } from './protocol.primitives.array.u16';
import { ArrayU32 } from './protocol.primitives.array.u32';
import { ArrayU64 } from './protocol.primitives.array.u64';
import { ArrayI8 } from './protocol.primitives.array.i8';
import { ArrayI16 } from './protocol.primitives.array.i16';
import { ArrayI32 } from './protocol.primitives.array.i32';
import { ArrayI64 } from './protocol.primitives.array.i64';
import { ArrayF32 } from './protocol.primitives.array.f32';
import { ArrayF64 } from './protocol.primitives.array.f64';
import { ArrayBool } from './protocol.primitives.array.bool';
import { ArrayStrUTF8 } from './protocol.primitives.array.string.utf8';
import { Option, Enum } from './protocol.primitives.enum';
import { Primitive } from './protocol.primitives.interface';

// injectable
type u8Alias = u8; const u8Alias = u8;
type u16Alias = u16; const u16Alias = u16;
type u32Alias = u32; const u32Alias = u32;
type u64Alias = u64; const u64Alias = u64;
type i8Alias = i8; const i8Alias = i8;
type i16Alias = i16; const i16Alias = i16;
type i32Alias = i32; const i32Alias = i32;
type i64Alias = i64; const i64Alias = i64;
type f32Alias = f32; const f32Alias = f32;
type f64Alias = f64; const f64Alias = f64;
type boolAlias = bool; const boolAlias = bool;
type StrUTF8Alias = StrUTF8; const StrUTF8Alias = StrUTF8;
type ArrayU8Alias = ArrayU8; const ArrayU8Alias = ArrayU8;
type ArrayU16Alias = ArrayU16; const ArrayU16Alias = ArrayU16;
type ArrayU32Alias = ArrayU32; const ArrayU32Alias = ArrayU32;
type ArrayU64Alias = ArrayU64; const ArrayU64Alias = ArrayU64;
type ArrayI8Alias = ArrayI8; const ArrayI8Alias = ArrayI8;
type ArrayI16Alias = ArrayI16; const ArrayI16Alias = ArrayI16;
type ArrayI32Alias = ArrayI32; const ArrayI32Alias = ArrayI32;
type ArrayI64Alias = ArrayI64; const ArrayI64Alias = ArrayI64;
type ArrayF32Alias = ArrayF32; const ArrayF32Alias = ArrayF32;
type ArrayF64Alias = ArrayF64; const ArrayF64Alias = ArrayF64;
type ArrayBoolAlias = ArrayBool; const ArrayBoolAlias = ArrayBool;
type ArrayStrUTF8Alias = ArrayStrUTF8; const ArrayStrUTF8Alias = ArrayStrUTF8;
type OptionAlias = Option<any>; const OptionAlias = Option;
type EnumAlias = Enum; const EnumAlias = Enum;
type PrimitiveAlias = Primitive<any>; const PrimitiveAlias = Primitive;

export namespace Primitives {
    export const u8 = u8Alias; export type u8 = u8Alias;
    export const u16 = u16Alias; export type u16 = u16Alias;
    export const u32 = u32Alias; export type u32 = u32Alias;
    export const u64 = u64Alias; export type u64 = u64Alias;
    export const i8 = i8Alias; export type i8 = i8Alias;
    export const i16 = i16Alias; export type i16 = i16Alias;
    export const i32 = i32Alias; export type i32 = i32Alias;
    export const i64 = i64Alias; export type i64 = i64Alias;
    export const f32 = f32Alias; export type f32 = f32Alias;
    export const f64 = f64Alias; export type f64 = f64Alias;
    export const bool = boolAlias; export type bool = boolAlias;
    export const StrUTF8 = StrUTF8Alias; export type StrUTF8 = StrUTF8Alias;
    export const ArrayU8 = ArrayU8Alias; export type ArrayU8 = ArrayU8Alias;
    export const ArrayU16 = ArrayU16Alias; export type ArrayU16 = ArrayU16Alias;
    export const ArrayU32 = ArrayU32Alias; export type ArrayU32 = ArrayU32Alias;
    export const ArrayU64 = ArrayU64Alias; export type ArrayU64 = ArrayU64Alias;
    export const ArrayI8 = ArrayI8Alias; export type ArrayI8 = ArrayI8Alias;
    export const ArrayI16 = ArrayI16Alias; export type ArrayI16 = ArrayI16Alias;
    export const ArrayI32 = ArrayI32Alias; export type ArrayI32 = ArrayI32Alias;
    export const ArrayI64 = ArrayI64Alias; export type ArrayI64 = ArrayI64Alias;
    export const ArrayF32 = ArrayF32Alias; export type ArrayF32 = ArrayF32Alias;
    export const ArrayF64 = ArrayF64Alias; export type ArrayF64 = ArrayF64Alias;
    export const ArrayBool = ArrayBoolAlias; export type ArrayBool = ArrayBoolAlias;
    export const ArrayStrUTF8 = ArrayStrUTF8Alias; export type ArrayStrUTF8 = ArrayStrUTF8Alias;
    export const Option = OptionAlias; export type Option = OptionAlias;
    export const Enum = EnumAlias; export type Enum = EnumAlias;
    export const Primitive = PrimitiveAlias; export type Primitive = PrimitiveAlias;
}
