refresh_rate: 1 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/lib-test.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: debug
  appenders:
    - stdout
    - requests
loggers:
  app::requests:
    level: debug
    appenders:
      - requests
    additive: true