[package]
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>"]
edition = "2018"
name = "fiber-cli"
version = "0.1.0"
[dependencies]
bytes = "*"
regex = "*"
ring = "0.16.20"
data-encoding = "2.3.2"
toml = "0.5.8"